#!/usr/bin/env python3
#
#  Copyright (c) 2026 Blake McBride
#  All rights reserved.
#
#  Rasterise an outline face into the two tables src/gfx/font_face.c holds:
#  a one-bit strike, which is what the image's StrikeFont draws from and what
#  decides every measurement it makes, and an eight-bit coverage map of the
#  same glyphs at the same advances, which is what the VM composites when it
#  recognises a blit as text.  The two must agree on advances to the pixel:
#  the image lays out from the first and the screen shows the second.
#
#  The source face is not vendored.  This runs against a font already on the
#  machine, records what it used in the generated file, and the OUTPUT is
#  what is checked in -- so a build needs no font installed, and the licence
#  obligation is on a derivative whose origin is written down.
#
#  Usage: tools/make_font.py <font.ttf> <pixel size> <output dir>
#  Writes font_face.h (the numbers) and font_face.c (the tables) there.
import sys
from PIL import Image, ImageDraw, ImageFont

path, size, outdir = sys.argv[1], int(sys.argv[2]), sys.argv[3]
face = ImageFont.truetype(path, size)
ascent, descent = face.getmetrics()
HEIGHT = ascent + descent
FIRST, LAST = 0, 127

def advance_of(code):
    ch = chr(code)
    if code < 32 or code > 126:
        ch = ' '
    return max(1, int(round(face.getlength(ch))))

adv = [advance_of(c) for c in range(FIRST, LAST + 1)]
xtab = [0]
for a in adv:
    xtab.append(xtab[-1] + a)
width = xtab[-1]
if width % 16:                      # the strike is a WordArray; pad to a word
    width += 16 - (width % 16)

def render(mode, aa):
    im = Image.new(mode, (width, HEIGHT), 0)
    d = ImageDraw.Draw(im)
    for code in range(32, 127):
        d.text((xtab[code - FIRST], ascent), chr(code), font=face,
               fill=255 if aa else 1, anchor="ls")
    return im

bits = render("1", False)
cov  = render("L", True)


banner = """/*
 *  Copyright (c) 2026 Blake McBride
 *  All rights reserved.
 *
 *  GENERATED by tools/make_font.py -- do not edit.
 *
 *  A rasterisation of
 *
 *      %s
 *      %s, %d pixels
 *
 *  Adwaita Sans is a fork of Inter and is under the SIL Open Font License
 *  1.1; see src/gfx/LICENSE.font, copied from the system package.  These
 *  tables are a derivative work of it: the glyph shapes are the face's,
 *  sampled onto this system's pixel grid.  Nothing here is a font file and
 *  nothing here can be installed as one -- it is ninety-five pictures of
 *  letters at one size.
 */
""" % (path, face.getname()[0], size)

h = open(outdir + "/font_face.h", "w")
h.write(banner)
h.write("""
#ifndef ST_FONT_FACE_H
#define ST_FONT_FACE_H

/*
 *  The cell, and the two tables that fill it.
 *
 *  ST_FONT_STRIKE is one bit and is the IMAGE's model of the text: the
 *  StrikeFont built from it answers every width the image measures, so it
 *  alone decides layout.  ST_FONT_COVERAGE is eight bits, the same glyphs at
 *  the same advances, and is what reaches the screen -- the VM composites it
 *  wherever it recognises a blit as coming from the strike.  They must agree
 *  on advances to the pixel or the two disagree about where a letter is.
 */
""")
h.write("#define ST_FONT_CODES          %d\n" % (LAST - FIRST + 1))
h.write("#define ST_FONT_HEIGHT         %d\n" % HEIGHT)
h.write("#define ST_FONT_ASCENT         %d\n" % ascent)
h.write("#define ST_FONT_DESCENT        %d\n" % descent)
h.write("#define ST_FONT_MAX_WIDTH      %d\n" % max(adv))
h.write("#define ST_FONT_STRIKE_WIDTH   %d\n" % width)
h.write("#define ST_FONT_STRIKE_BYTES   (ST_FONT_STRIKE_WIDTH / 8)\n")
h.write("""
#endif  /*  ST_FONT_FACE_H  */
""")
h.close()

c = open(outdir + "/font_face.c", "w")
c.write(banner)
c.write('\n#include "font.h"\n\n')
c.write("/*  Where each code begins in the strike, and one past the last.  */\n")
c.write("const uint16_t  ST_FONT_XTABLE[ST_FONT_CODES + 1] = {\n")
for i in range(0, len(xtab), 16):
    c.write("    " + ",".join("%4d" % v for v in xtab[i:i+16]) + ",\n")
c.write("};\n\n")
px = bits.load()
c.write("/*  Row 0 is the top; bit 7 of each byte is its leftmost pixel.  */\n")
c.write("const uint8_t   ST_FONT_STRIKE[ST_FONT_HEIGHT][ST_FONT_STRIKE_BYTES] = {\n")
for y in range(HEIGHT):
    row = []
    for byte in range(width // 8):
        v = 0
        for b in range(8):
            if px[byte*8 + b, y]:
                v |= 1 << (7 - b)
        row.append(v)
    c.write("    { " + ",".join("0x%02X" % v for v in row) + " },\n")
c.write("};\n\n")
cx = cov.load()
c.write("/*  Ink coverage, 0 none to 255 full, one byte a pixel.  */\n")
c.write("const uint8_t   ST_FONT_COVERAGE[ST_FONT_HEIGHT][ST_FONT_STRIKE_WIDTH] = {\n")
for y in range(HEIGHT):
    c.write("    {" + ",".join("%d" % cx[x, y] for x in range(width)) + "},\n")
c.write("};\n")
c.close()
sys.stderr.write("height %d ascent %d descent %d strike %d px, max advance %d\n"
                 % (HEIGHT, ascent, descent, width, max(adv)))
