/*
 *  Copyright (c) 2026 Blake McBride
 *  All rights reserved.
 *
 *  GENERATED by tools/make_font.py -- do not edit.
 *
 *  A rasterisation of
 *
 *      /usr/share/fonts/rsms-inter-fonts/Inter-Regular.ttf
 *      Inter, 18 pixels, 3 rows of lead
 *      sha256 40d692fce188e4471e2b3cba937be967878f631ad3ebbbdcd587687c7ebe0c82
 *
 *  The hash is of the SOURCE FONT, not of this file.  Reproducing these
 *  tables needs that exact font: "Inter" is not one font, and two versions
 *  of a family rasterise differently at the same size.  Regenerate with
 *  `make font' or tools/make_font.py, then rebuild -- and rebuild any image
 *  as well, because the face is compiled into an image at bootstrap and an
 *  image cannot be shown a different one.
 *
 *  The face is under the SIL Open Font License 1.1; see
 *  src/gfx/LICENSE.font, and doc/LICENSING.md for what that obliges.  These
 *  tables are a derivative work of it: the glyph shapes are the face's,
 *  sampled onto this system's pixel grid.  Nothing here is a font file and
 *  nothing here can be installed as one -- it is ninety-five pictures of
 *  letters at one size.
 */

#ifndef ST_FONT_FACE_H
#define ST_FONT_FACE_H

/*
 *  The cell, and the two tables that fill it.
 *
 *  ST_FONT_STRIKE is one bit and is the IMAGE's model of the text: the
 *  StrikeFont built from it answers every width the image measures, so it
 *  alone decides layout.  ST_FONT_COVERAGE is eight bits, the same glyphs at
 *  the same advances, and is what reaches the screen -- the VM composites it
 *  wherever it recognises a blit as coming from the strike.  They must agree
 *  on advances to the pixel or the two disagree about where a letter is.
 */
#define ST_FONT_CODES          128
#define ST_FONT_HEIGHT         26
#define ST_FONT_ASCENT         18
#define ST_FONT_DESCENT        8
#define ST_FONT_LEAD           3
#define ST_FONT_MAX_WIDTH      18
#define ST_FONT_STRIKE_WIDTH   1136
#define ST_FONT_STRIKE_BYTES   (ST_FONT_STRIKE_WIDTH / 8)

#endif  /*  ST_FONT_FACE_H  */
